### ISSUE TITLE
Inner not used?

### ISSUE THREAD

**Issue by carsonfarmer** [tianzhao/rxjs#1]
I guess this is more of a question than an issue, but is [`inner` here](https://github.com/tianzhao/rxjs/blob/04c94c33ce7abc03ba289734c601c229d579e0ee/debugging/rxjs.js#L563) never actually referenced outside this closure? Is this just to keep a reference to the inner subscription? The Subscription class doesn't actually expose this property anywhere else...

**Comment by tianzhao** [comment]
> I guess this is more of a question than an issue, but is [`inner` here](https://github.com/tianzhao/rxjs/blob/04c94c33ce7abc03ba289734c601c229d579e0ee/debugging/rxjs.js#L563) never actually referenced outside this closure? Is this just to keep a reference to the inner subscription? The Subscription class doesn't actually expose this property anywhere else...

You are right. The 'inner' field is not used within the library. It is there so that we can traverse the subscription graph. Its purpose is similar to the 'child' and 'source' fields to help user navigate the subscription graph in case of an error. The static combinators are often defined using more primitive ones. For example, 'find' is defined using 'filter' and 'take'. If necessary, user can check the implementation of 'find' by following the 'inner' reference.

**Comment by carsonfarmer** [comment]
Aha, gotcha, this makes sense. I've been attempting to fully type this library and a few of these have cropped up. Adding things like child, source, and inner as optionals fixes this, and forces me to explicitly check that they are actually defined in downstream code.
